### ISSUE TITLE
Shell script suggestion: run shellcheck on it and fix the issues it finds

### ISSUE THREAD

**Issue by koalaman** [WebParakeet/webp-octa-installer#2]

**Comment by alwaysontop617** [comment]
$ shellcheck myscript
 
Line 83:
if [ -n "$(command -v $1)" ]; then
                      ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 87:
    read -p "Do you wish to install $1?" yn
    ^-- SC2162: read without -r will mangle backslashes.
 
Line 89:
        [Yy]* ) $package -y -qq install $1; break;;
                                        ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 97:
   if [ -n "$(command -v $1)" ]; then
                         ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 98:
   val="$(service $1 start)"
   ^-- SC2034: val appears unused. Verify it or export it.
                  ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 105:
    wget --progress=dot $url 2>&1 | grep --line-buffered "%" | \
                        ^-- SC2086: Double quote to prevent globbing and word splitting.
 
Line 125:
md5=`md5sum master.zip | awk '{ print $1 }'`  
    ^-- SC2006: Use $(..) instead of legacy `..`.
 
Line 135:
quiet="$(rm -rf temp)"
^-- SC2034: quiet appears unused. Verify it or export it.

$

**Comment by alwaysontop617** [comment]
$ shellcheck myscript
No issues detected!

$
